github.com:
    users:
        k-milchev_dynamo:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: k-milchev_dynamo
